labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        > [!IMPORTANT]
        > Please search existing [Discussions](https://github.com/jsattler/BetterCapture/discussions?discussions_q=category%3A%22Bug+Reports%22) and [Issues](https://github.com/jsattler/BetterCapture/issues?q=sort%3Areactions-desc) before opening a new bug report to avoid duplicates.

  - type: markdown
    attributes:
      value: "# Bug Report"

  - type: dropdown
    attributes:
      label: Version
      description: What version of BetterCapture are you running? You can find this in Settings > General.
      options:
        - v2026.1.3
        - v2026.1.2
        - v2026.1.1
        - v2026.1.0
    validations:
      required: true

  - type: input
    attributes:
      label: macOS Version
      description: What version of macOS are you running? You can find this in  > About This Mac.
      placeholder: "26.1 (Tahoe)"
    validations:
      required: true

  - type: textarea
    attributes:
      label: What happened?
      description: Describe the bug you encountered.
      placeholder: Tell us what you see!
    validations:
      required: true

  - type: textarea
    attributes:
      label: What did you expect to happen?
      description: Describe the behavior you expected.
      placeholder: Tell us what you expected!
    validations:
      required: false

  - type: textarea
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce this issue?
      placeholder: |
        1. Go to...
        2. Click on...
        3. See error...
    validations:
      required: false

  - type: markdown
    attributes:
      value: "# Capture Configuration"

  - type: dropdown
    attributes:
      label: Video Codec
      description: Which video codec are you using?
      options:
        - H.264
        - HEVC (H.265)
        - ProRes 422
        - ProRes 4444
        - Not sure
    validations:
      required: true

  - type: dropdown
    attributes:
      label: Audio Codec
      description: Which audio codec are you using?
      options:
        - AAC
        - PCM
        - Not sure
    validations:
      required: true

  - type: dropdown
    attributes:
      label: Container Format
      description: Which container format are you using?
      options:
        - MOV
        - MP4
        - Not sure
    validations:
      required: true

  - type: dropdown
    attributes:
      label: Alpha Channel
      description: Is alpha channel capture enabled?
      options:
        - Enabled
        - Disabled
    validations:
      required: false

  - type: dropdown
    attributes:
      label: HDR
      description: Is HDR capture enabled?
      options:
        - Enabled
        - Disabled
    validations:
      required: false

  - type: checkboxes
    attributes:
      label: Content Filters
      description: Which content filters are active?
      options:
        - label: Show Cursor
        - label: Show Wallpaper
        - label: Show Menu Bar
        - label: Show Dock
        - label: Show Window Shadows
        - label: Show BetterCapture

  - type: dropdown
    attributes:
      label: Microphone
      description: Is microphone capture enabled?
      options:
        - Enabled
        - Disabled
    validations:
      required: true

  - type: markdown
    attributes:
      value: "# Acknowledgements"

  - type: checkboxes
    attributes:
      label: "I confirm that:"
      options:
        - label: I have searched existing Discussions and Issues and this is not a duplicate.
          required: true
