labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        > [!IMPORTANT]
        > Please search existing [Discussions](https://github.com/jsattler/BetterCapture/discussions?discussions_q=category%3AIdeas) and [Issues](https://github.com/jsattler/BetterCapture/issues?q=sort%3Areactions-desc) before opening a new feature request to avoid duplicates.

  - type: markdown
    attributes:
      value: "# Feature Request"

  - type: textarea
    attributes:
      label: Problem Statement
      description: |
        Describe the problem or limitation you are experiencing. What workflow is difficult or impossible today?
      placeholder: |
        I often need to capture a specific window region, but currently I can only capture the entire window or screen.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Proposed Solution
      description: |
        Describe the feature or change you would like to see. Be as specific as possible about the expected behavior.
      placeholder: |
        Add an option to select a custom region within a window before starting a capture.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Alternatives Considered
      description: |
        Have you considered any alternative solutions or workarounds? If so, please describe them.
      placeholder: |
        I currently crop the recording after capture using a separate video editor, but this adds extra steps.
    validations:
      required: false

  - type: textarea
    attributes:
      label: Additional Context
      description: |
        Add any other context, screenshots, mockups, or references that help illustrate your request.
    validations:
      required: false

  - type: markdown
    attributes:
      value: "# Acknowledgements"

  - type: checkboxes
    attributes:
      label: "I confirm that:"
      options:
        - label: I have searched existing Discussions and Issues and this is not a duplicate.
          required: true
